#For HTML Layout and FileAppender
#Specify Logger level to retrieve the log messages
log4j.rootLogger=DEBUG,R
#Specify appender 
log4j.appender.R=org.apache.log4j.FileAppender
#Specify file name
log4j.appender.R.File=info.html
#Disabling append mode on file
log4j.appender.R.append=false
#Specify Layout
log4j.appender.R.layout=org.apache.log4j.HTMLLayout