
spring.application.name=api-gateway
server.port=9191
eureka.instance.prefer-ip-address=true

jwt.secret=z1HYK7nO0QacClh2UgL6/0lM5aA6fTjGRQwX59pjE0E=
# Config Server
#spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=optional:configserver:http://config-server:8888
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Eureka server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Expose Actuator endpoints
management.endpoints.web.exposure.include=*

# Routes
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://order-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/order-api/**

spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://inventory-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/inventory-api/**

spring.cloud.gateway.routes[2].id=product-service
spring.cloud.gateway.routes[2].uri=lb://product-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/product-api/**

# Route for Auth-Service
spring.cloud.gateway.routes[3].id=auth-service
spring.cloud.gateway.routes[3].uri=lb://auth-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth-api/**

# Route for OAuth2 endpoints (token, authorize, jwks)
spring.cloud.gateway.routes[4].id=auth-oauth2
spring.cloud.gateway.routes[4].uri=lb://auth-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/oauth2/**

# Route for login page (if you use form login)
spring.cloud.gateway.routes[5].id=auth-login
spring.cloud.gateway.routes[5].uri=lb://auth-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/login

# Route for Cart Service
spring.cloud.gateway.routes[6].id=cart-service
spring.cloud.gateway.routes[6].uri=lb://cart-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/cart-api/**



spring.cloud.gateway.routes[7].id=wishlist-service
spring.cloud.gateway.routes[7].uri=lb://WISHLIST-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/favorite-api/**

spring.cloud.gateway.routes[8].id=review-service
spring.cloud.gateway.routes[8].uri=lb://review-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/review-api/**

# Route for Payment Service
spring.cloud.gateway.routes[9].id=payment-service
spring.cloud.gateway.routes[9].uri=lb://payment-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/payment-api/**

